## ewf-wfp-02-02-01 - Snow Cover Characterization Time Series

Snow Cover Characterization Time Series

---

### <a name="service">Service definition

In [1]:
service = dict([('title', 'Snow Cover Characterization Time Series'),
                ('abstract', 'Snow Cover Characterization Time Series'),
                ('id', 'ewf-wfp-02-02-01')])

In [2]:
regionOfInterest = dict([('id', 'regionOfInterest'),
                         ('value', 'POLYGON((25.0 48.0, 94.0 48.0, 94.0 23.1, 25.0 23.1, 25.0 48.0))'),
                         ('title', 'WKT Polygon for the Region of Interest'),
                         ('abstract', 'Set the value of WKT Polygon')])

In [3]:
nameOfRegion = dict([('id', 'nameOfRegion'),
                     ('value', 'CentralAsia'),
                     ('title', 'Name of Region'),
                     ('abstract', 'Name of the region of interest'),
                     ('minOccurs', '1')])

### <a name="runtime">Runtime parameter definition

**Input identifiers**

This is the MDOIS stack of products' identifiers

In [4]:
input_identifiers = ('MOD10A2.A2015001.h19v04.006.2016172230552.hdf',
                     'MOD10A2.A2015001.h19v05.006.2016172224844.hdf',
                     'MOD10A2.A2015001.h20v04.006.2016172230600.hdf',
                     'MOD10A2.A2015001.h20v05.006.2016172234130.hdf',
                     'MOD10A2.A2015009.h19v04.006.2016173202655.hdf',
                     'MOD10A2.A2015009.h19v05.006.2016173201100.hdf',
                     'MOD10A2.A2015009.h20v04.006.2016173201300.hdf',
                     'MOD10A2.A2015009.h20v05.006.2016173203828.hdf',
                     'MOD10A2.A2015017.h19v04.006.2016173230827.hdf',
                     'MOD10A2.A2015017.h19v05.006.2016173222259.hdf',
                     'MOD10A2.A2015017.h20v04.006.2016173205042.hdf',
                     'MOD10A2.A2015017.h20v05.006.2016173203722.hdf')

input_identifiers = ('MOD10A2.A2015217.h19v04.006.2016181040203.hdf','MOD10A2.A2015217.h19v05.006.2016181041147.hdf','MOD10A2.A2015217.h20v04.006.2016181040703.hdf','MOD10A2.A2015217.h20v05.006.2016181041352.hdf','MOD10A2.A2015225.h19v04.006.2016181061932.hdf','MOD10A2.A2015225.h19v05.006.2016181061952.hdf','MOD10A2.A2015225.h20v04.006.2016181061951.hdf','MOD10A2.A2015225.h20v05.006.2016181061109.hdf','MOD10A2.A2015233.h19v04.006.2016181065423.hdf','MOD10A2.A2015233.h19v05.006.2016181071440.hdf','MOD10A2.A2015233.h20v04.006.2016181070735.hdf','MOD10A2.A2015233.h20v05.006.2016181065807.hdf','MOD10A2.A2015241.h19v04.006.2016181062033.hdf','MOD10A2.A2015241.h19v05.006.2016181051646.hdf','MOD10A2.A2015241.h20v04.006.2016181053544.hdf','MOD10A2.A2015241.h20v05.006.2016181053542.hdf','MOD10A2.A2015249.h19v04.006.2016181080505.hdf','MOD10A2.A2015249.h19v05.006.2016181070522.hdf','MOD10A2.A2015249.h20v04.006.2016181070456.hdf','MOD10A2.A2015249.h20v05.006.2016181071344.hdf','MOD10A2.A2015257.h19v04.006.2016181065140.hdf','MOD10A2.A2015257.h19v05.006.2016181064608.hdf','MOD10A2.A2015257.h20v04.006.2016181070354.hdf','MOD10A2.A2015257.h20v05.006.2016181064104.hdf','MOD10A2.A2015265.h19v04.006.2016181065815.hdf','MOD10A2.A2015265.h19v05.006.2016181064618.hdf','MOD10A2.A2015265.h20v04.006.2016181072259.hdf','MOD10A2.A2015265.h20v05.006.2016181070932.hdf','MOD10A2.A2015273.h19v04.006.2016181062047.hdf','MOD10A2.A2015273.h19v05.006.2016181062026.hdf','MOD10A2.A2015273.h20v04.006.2016181062930.hdf','MOD10A2.A2015273.h20v05.006.2016181061637.hdf','MOD10A2.A2015281.h19v04.006.2016181201907.hdf','MOD10A2.A2015281.h19v05.006.2016181202801.hdf','MOD10A2.A2015281.h20v04.006.2016181201807.hdf','MOD10A2.A2015281.h20v05.006.2016181202922.hdf','MOD10A2.A2015289.h19v04.006.2016182032251.hdf','MOD10A2.A2015289.h19v05.006.2016182030630.hdf','MOD10A2.A2015289.h20v04.006.2016182032143.hdf','MOD10A2.A2015289.h20v05.006.2016182031542.hdf','MOD10A2.A2015297.h19v04.006.2016182032350.hdf','MOD10A2.A2015297.h19v05.006.2016182031829.hdf','MOD10A2.A2015297.h20v04.006.2016182032348.hdf','MOD10A2.A2015297.h20v05.006.2016182024408.hdf','MOD10A2.A2015305.h19v04.006.2016182033801.hdf','MOD10A2.A2015305.h19v05.006.2016182033426.hdf','MOD10A2.A2015305.h20v04.006.2016182034126.hdf','MOD10A2.A2015305.h20v05.006.2016182034127.hdf','MOD10A2.A2015313.h19v04.006.2016182040147.hdf','MOD10A2.A2015313.h19v05.006.2016182040153.hdf','MOD10A2.A2015313.h20v04.006.2016182033808.hdf','MOD10A2.A2015313.h20v05.006.2016182034309.hdf','MOD10A2.A2015321.h19v04.006.2016182042502.hdf','MOD10A2.A2015321.h19v05.006.2016182042459.hdf','MOD10A2.A2015321.h20v04.006.2016182042501.hdf','MOD10A2.A2015321.h20v05.006.2016182042344.hdf','MOD10A2.A2015329.h19v04.006.2016182041522.hdf','MOD10A2.A2015329.h19v05.006.2016182040439.hdf','MOD10A2.A2015329.h20v04.006.2016182043811.hdf','MOD10A2.A2015329.h20v05.006.2016182042612.hdf','MOD10A2.A2015337.h19v04.006.2016182044041.hdf','MOD10A2.A2015337.h19v05.006.2016182042222.hdf','MOD10A2.A2015337.h20v04.006.2016182042340.hdf','MOD10A2.A2015337.h20v05.006.2016182041747.hdf','MOD10A2.A2015345.h19v04.006.2016182155822.hdf','MOD10A2.A2015345.h19v05.006.2016182155815.hdf','MOD10A2.A2015345.h20v04.006.2016182160042.hdf','MOD10A2.A2015345.h20v05.006.2016182155452.hdf','MOD10A2.A2015353.h19v04.006.2016182205041.hdf','MOD10A2.A2015353.h19v05.006.2016182205255.hdf','MOD10A2.A2015353.h20v04.006.2016182204052.hdf','MOD10A2.A2015353.h20v05.006.2016182204052.hdf','MOD10A2.A2015361.h19v04.006.2016183124258.hdf','MOD10A2.A2015361.h19v05.006.2016183123821.hdf','MOD10A2.A2015361.h20v04.006.2016183124250.hdf','MOD10A2.A2015361.h20v05.006.2016183124103.hdf','MOD10A2.A2016001.h19v04.006.2016183134249.hdf','MOD10A2.A2016001.h19v05.006.2016183134250.hdf','MOD10A2.A2016001.h20v04.006.2016183134934.hdf','MOD10A2.A2016001.h20v05.006.2016183134219.hdf','MOD10A2.A2016009.h19v04.006.2016182225710.hdf','MOD10A2.A2016009.h19v05.006.2016182225713.hdf','MOD10A2.A2016009.h20v04.006.2016182230041.hdf','MOD10A2.A2016009.h20v05.006.2016182230038.hdf','MOD10A2.A2016017.h19v04.006.2016026072835.hdf','MOD10A2.A2016017.h19v05.006.2016026072809.hdf','MOD10A2.A2016017.h20v04.006.2016026072827.hdf','MOD10A2.A2016017.h20v05.006.2016026072830.hdf','MOD10A2.A2016025.h19v04.006.2016035164135.hdf','MOD10A2.A2016025.h19v05.006.2016035161920.hdf','MOD10A2.A2016025.h20v04.006.2016035161812.hdf','MOD10A2.A2016025.h20v05.006.2016035162249.hdf','MOD10A2.A2016033.h19v04.006.2016043141801.hdf','MOD10A2.A2016033.h19v05.006.2016043142308.hdf','MOD10A2.A2016033.h20v04.006.2016043141936.hdf','MOD10A2.A2016033.h20v05.006.2016043141732.hdf','MOD10A2.A2016041.h19v04.006.2016050071609.hdf','MOD10A2.A2016041.h19v05.006.2016050071329.hdf','MOD10A2.A2016041.h20v04.006.2016050072409.hdf','MOD10A2.A2016041.h20v05.006.2016050072227.hdf','MOD10A2.A2016065.h19v04.006.2016110192134.hdf','MOD10A2.A2016065.h19v05.006.2016110191744.hdf','MOD10A2.A2016065.h20v04.006.2016110192217.hdf','MOD10A2.A2016065.h20v05.006.2016110191835.hdf','MOD10A2.A2016073.h19v04.006.2016110194154.hdf','MOD10A2.A2016073.h19v05.006.2016110193845.hdf','MOD10A2.A2016073.h20v04.006.2016110194056.hdf','MOD10A2.A2016073.h20v05.006.2016110193919.hdf','MOD10A2.A2016081.h19v04.006.2016110200007.hdf','MOD10A2.A2016081.h19v05.006.2016110195736.hdf','MOD10A2.A2016081.h20v04.006.2016110200229.hdf','MOD10A2.A2016081.h20v05.006.2016110195910.hdf','MOD10A2.A2016089.h19v04.006.2016110203223.hdf','MOD10A2.A2016089.h19v05.006.2016110202008.hdf','MOD10A2.A2016089.h20v04.006.2016110205818.hdf','MOD10A2.A2016089.h20v05.006.2016110204545.hdf','MOD10A2.A2016097.h19v04.006.2016106221629.hdf','MOD10A2.A2016097.h19v05.006.2016106221517.hdf','MOD10A2.A2016097.h20v04.006.2016106221639.hdf','MOD10A2.A2016097.h20v05.006.2016106221302.hdf','MOD10A2.A2016105.h19v04.006.2016114082452.hdf','MOD10A2.A2016105.h19v05.006.2016114082255.hdf','MOD10A2.A2016105.h20v04.006.2016114075955.hdf','MOD10A2.A2016105.h20v05.006.2016114074736.hdf','MOD10A2.A2016113.h19v04.006.2016123132422.hdf','MOD10A2.A2016113.h19v05.006.2016123133639.hdf','MOD10A2.A2016113.h20v04.006.2016123132424.hdf','MOD10A2.A2016113.h20v05.006.2016123132417.hdf','MOD10A2.A2016121.h19v04.006.2016130154408.hdf','MOD10A2.A2016121.h19v05.006.2016130152344.hdf','MOD10A2.A2016121.h20v04.006.2016130151711.hdf','MOD10A2.A2016121.h20v05.006.2016130152048.hdf','MOD10A2.A2016129.h19v04.006.2016140154151.hdf','MOD10A2.A2016129.h19v05.006.2016140153820.hdf','MOD10A2.A2016129.h20v04.006.2016140154121.hdf','MOD10A2.A2016129.h20v05.006.2016140153448.hdf','MOD10A2.A2016137.h19v04.006.2016147150819.hdf','MOD10A2.A2016137.h19v05.006.2016147151208.hdf','MOD10A2.A2016137.h20v04.006.2016147144543.hdf','MOD10A2.A2016137.h20v05.006.2016147145117.hdf','MOD10A2.A2016145.h19v04.006.2016155181856.hdf','MOD10A2.A2016145.h19v05.006.2016155181506.hdf','MOD10A2.A2016145.h20v04.006.2016155181651.hdf','MOD10A2.A2016145.h20v05.006.2016155181433.hdf','MOD10A2.A2016153.h19v04.006.2016166184550.hdf','MOD10A2.A2016153.h19v05.006.2016166184317.hdf','MOD10A2.A2016153.h20v04.006.2016166184434.hdf','MOD10A2.A2016153.h20v05.006.2016166184550.hdf','MOD10A2.A2016161.h19v04.006.2016170072859.hdf','MOD10A2.A2016161.h19v05.006.2016170072607.hdf','MOD10A2.A2016161.h20v04.006.2016170073849.hdf','MOD10A2.A2016161.h20v05.006.2016170073611.hdf','MOD10A2.A2016169.h19v04.006.2016184041911.hdf','MOD10A2.A2016169.h19v05.006.2016184040300.hdf','MOD10A2.A2016169.h20v04.006.2016184041926.hdf','MOD10A2.A2016169.h20v05.006.2016184041852.hdf','MOD10A2.A2016177.h19v04.006.2016188012837.hdf','MOD10A2.A2016177.h19v05.006.2016188012519.hdf','MOD10A2.A2016177.h20v04.006.2016188012552.hdf','MOD10A2.A2016177.h20v05.006.2016188012443.hdf','MOD10A2.A2016185.h19v04.006.2016194193853.hdf','MOD10A2.A2016185.h19v05.006.2016194193610.hdf','MOD10A2.A2016185.h20v04.006.2016194194258.hdf','MOD10A2.A2016185.h20v05.006.2016194194306.hdf','MOD10A2.A2016193.h19v04.006.2016202083932.hdf','MOD10A2.A2016193.h19v05.006.2016202085128.hdf','MOD10A2.A2016193.h20v04.006.2016202083722.hdf','MOD10A2.A2016193.h20v05.006.2016202083631.hdf','MOD10A2.A2016201.h19v04.006.2016215123536.hdf','MOD10A2.A2016201.h19v05.006.2016215123748.hdf','MOD10A2.A2016201.h20v04.006.2016215123826.hdf','MOD10A2.A2016201.h20v05.006.2016215123656.hdf','MOD10A2.A2016209.h19v04.006.2016222123114.hdf','MOD10A2.A2016209.h19v05.006.2016222122928.hdf','MOD10A2.A2016209.h20v04.006.2016222123118.hdf','MOD10A2.A2016209.h20v05.006.2016222122820.hdf')

**Input references**

This is the MODIS stack catalogue references

In [5]:
input_references = tuple(['https://catalog.terradue.com/modis/search?uid={0}'.format(pid) for pid in input_identifiers])

**Data path**

This path defines where the data is staged-in. 

In [6]:
data_path = "/workspace/data/MOD10A2"

**Aux folders**

In [7]:
output_folder = ''

In [8]:
temp_folder = 'temp'

#### Import Modules

In [9]:
import os
import shutil

import sys
import string
import numpy as np
from osgeo import gdal, ogr, osr
from shapely.wkt import loads

import math

import datetime

import pdb

from convertmodis_gdal import createMosaicGDAL

#### Auxiliary vars

In [10]:
# If True loads all imagens in one var (consumes a lot of memory!!)
# If False loads image when it needs (takes a lot of time!!)
load_all_data = False

# plots and etc.
check_results = True

#### Auxiliary methods

In [23]:
# remove contents of a given folder
# used to clean a temporary folder
def rm_cfolder(folder):
    #folder = '/path/to/folder'
    for the_file in os.listdir(folder):
        file_path = os.path.join(folder, the_file)
        try:
            if os.path.isfile(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path): shutil.rmtree(file_path)
        except Exception as e:
            print(e)
            

def get_metadata(filepath):
    ds = gdal.Open(filepath)
    projection = ds.GetProjection()
    geotransform = ds.GetGeoTransform()
    no_data_value = ds.GetRasterBand(1).GetNoDataValue()
    data_type = ds.GetRasterBand(1).DataType
    return projection, geotransform, no_data_value, data_type

def get_matrix_list(image_list):
    mat_list = []
    for img in image_list:
        dataset = gdal.Open(img)
        product_array = dataset.GetRasterBand(1).ReadAsArray()
        mat_list.append(product_array)
        dataset = None
    return mat_list

def load_img_to_matrix (img_path):
    
    dataset = gdal.Open(img_path)
    product_array = dataset.GetRasterBand(1).ReadAsArray()
    return product_array


# computes matrix with the number of snow days
# used to compute 2) Count of number of snow days during the season
def get_snow_ndays (matrix_list):
    
    # Receives a list of strings containing the paths of the images
    # or
    # Receives a list of numpy arrays with the images loaded
    
    if isinstance(matrix_list[0], str):
        snow_ndays = np.full_like(load_img_to_matrix(matrix_list[0]), 0)
    else:
        snow_ndays = np.full_like(matrix_list[0], 0)
    
    
    for m in matrix_list:

        # NEW
        if isinstance(m, str):
            m = load_img_to_matrix (m)

        # convert each element to its binary sequence and counts the number os 1s
        snow_ndays_counter = np.vectorize(lambda m: format(m, 'b').count('1'))
        
        snow_ndays = snow_ndays + snow_ndays_counter(m)

    return snow_ndays




# given a string of 0s and 1s
# returns: num_of_1s - last number of consecutive numbers of 1s
#          max_num_of_1s_so_far - last max number of consecutive numbers of 1s
#          last_car - the last character ('0' or '1')
# it also recives those variables as input in order to apply it to a sequence os strings
# used to compute 3) Count of number of consecutive snow cover days
def count_of_major_consecutive_sc_days(sr, num_of_1s = 0, max_num_of_1s_so_far = 0, last_car = '0'):
    
    if isinstance(sr, str) and len(sr) == 8:
        pass
    else:
        # convert to binary sequence os 0s and 1s
        # fill with 0 to the extent of 8 chars
        # reverse order (because modis stores info in reverse order)
        sr = format(sr, 'b').zfill(8)[::-1]
    
    for c in sr:
        
        if c == '1' and last_car == '1':
            num_of_1s = num_of_1s + 1
            
        elif c == '1' and last_car == '0':
            
            if num_of_1s > max_num_of_1s_so_far:
                max_num_of_1s_so_far = num_of_1s
            
            num_of_1s = 1
            
        last_car = c
        if num_of_1s > max_num_of_1s_so_far:
            max_num_of_1s_so_far = num_of_1s
            
    return num_of_1s, max_num_of_1s_so_far, last_car

# Apply count_of_major_consecutive_sc_days to a list os matrices
# os sequences os 0s and 1s
# used to compute 3) Count of number of consecutive snow cover days
def get_max_sc_consecutive_ndays (matrix_list):
    

    num_of_1s = np.zeros(matrix_list[0].shape)
    max_num_of_1s_so_far = np.zeros(matrix_list[0].shape)  
    last_car = np.full(matrix_list[0].shape, ['0'],dtype=str)
    
    major_consecutive_sc_days_counter = np.vectorize(count_of_major_consecutive_sc_days)
    
    for m in matrix_list:
        num_of_1s, max_num_of_1s_so_far, last_car = major_consecutive_sc_days_counter(m, num_of_1s, max_num_of_1s_so_far, last_car)
    
    return max_num_of_1s_so_far


# find idexes of 1st image and 1st '1' in binary sequence
# input:
# sr - string of current binary sequence
# pos_current_img - index of current img
# pos_img1 - index of 1st img with snow
# pos_img2 - index of 2nd img with snow
# pos_1st_snow - pos [0-7] of 1st '1' in the binary sequence
#
# -1 used as nodata
#
# used to compute 4) Start and end date of snow cover season
def find_start_day_snow_season_idx(sr, pos_current_img, pos_img1 = -1, pos_img2 = -1, pos_1st_snow = -1):
    
    if isinstance(sr, str) and len(sr) == 8:
        pass
    else:
        # convert to binary sequence os 0s and 1s
        # fill with 0 to the extent of 8 chars
        # reverse order (because modis stores info in reverse order)
        sr = format(sr, 'b') #.zfill(8)[::-1]
        
    if '1' in sr: # if sr contains at least one 1
        
        if pos_img1 == -1:
            pos_img1 = pos_current_img
            pos_1st_snow = sr.zfill(8)[::-1].find('1')
        else:
            if pos_img2 == -1:
                pos_img2 = pos_current_img
            else:
                pass
            
    else:
        if pos_img1 == -1:
            pass
        else:
            pos_img1 = -1
            pos_1st_snow = -1
            
    return pos_img1, pos_img2, pos_1st_snow

    

# Apply find_start_day_snow_season_idx to a list of snow cover images
# used to compute 4) Start and end date of snow cover season
def get_start_day_snow_season (matrix_list, pos_img1 = None, pos_img2 = None, pos_1st_snow = None):
 
    if pos_img1 is None:
        pos_img1 = np.ones(matrix_list[0].shape) * -1
    if pos_img2 is None:
        pos_img2 = np.ones(matrix_list[0].shape) * -1
    if pos_1st_snow is None:
        pos_1st_snow = np.ones(matrix_list[0].shape) * -1
    
    start_day_snow_season_finder = np.vectorize(find_start_day_snow_season_idx)
    
    for idxsa in range(len(matrix_list)):
        
        pos_img1, pos_img2, pos_1st_snow = start_day_snow_season_finder(matrix_list[idxsa], idxsa, pos_img1, pos_img2, pos_1st_snow)
    
    return pos_img1, pos_1st_snow



def find_end_day_snow_season_idx(sr, pos_current_img, pos_img1 = -1, pos_img2 = -1, pos_1st_snow = -1):
    
    if isinstance(sr, str) and len(sr) == 8:
        pass
    else:
        # convert to binary sequence os 0s and 1s
        # fill with 0 to the extent of 8 chars
        # reverse order (because modis stores info in reverse order)
        sr = format(sr, 'b') #.zfill(8)[::-1]
        
    if '1' in sr: # if sr contains at least one 1
        
        if pos_img1 == -1:
            pass
        else:
            pos_img1 = -1
            pos_1st_snow = -1      
            
    else:
        
        if pos_img1 == -1:
            pos_img1 = pos_current_img
            #pos_1st_snow = sr.zfill(8)[::-1].find('1')
        else:
            if pos_img2 == -1:
                pos_img2 = pos_current_img
                pos_1st_snow = 7
            else:
                pass
            
    return pos_img1, pos_img2, pos_1st_snow



def get_end_day_snow_season (matrix_list, pos_img1 = None, pos_img2 = None, pos_1st_snow = None):

    
    if pos_img1 is None:
        pos_img1 = np.ones(matrix_list[0].shape) * -1
    if pos_img2 is None:
        pos_img2 = np.ones(matrix_list[0].shape) * -1
    if pos_1st_snow is None:
        pos_1st_snow = np.ones(matrix_list[0].shape) * -1

    
    end_day_snow_season_finder = np.vectorize(find_end_day_snow_season_idx)
    
    for idxsa in range(len(matrix_list)):
        
        pos_img1, pos_img2, pos_1st_snow = end_day_snow_season_finder(matrix_list[idxsa], idxsa, pos_img1, pos_img2, pos_1st_snow)
    
    return pos_img1, pos_1st_snow



    
    
#(COS DOY) is the cosine of the Julian date transformed to radians or degrees;
# that is, = cos (2 \pi t / 365) or cos(360º t / 365) and t is the Julian date of the valid time (the Julian date for January 1st is 1, and for October 31st it is 304)
# From Statistical Methods in the Atmospheric Sciences by Daniel S. Wilks
# used to compute 4) Start and end date of snow cover season
def date2COSDOY (date):
    # datetime.datetime(2019,12,30)
    return math.cos(2 * math.pi * date.timetuple().tm_yday / 365)

# given a list of dates,
# the index in that list and the index in the eight day sequence
# returns cos_doy
# used to compute 4) Start and end date of snow cover season
def indexes_to_cosdoy (dates, img_idx, eight_day_idx):
    
    if img_idx == -1:
        return -999
    
    date = dates[img_idx] + datetime.timedelta(days=eight_day_idx)
    return date2COSDOY(date)


# Computes cos_doy for a given image index and binary position
# py_dates - ordered list of date in python datetime format
# pos_img - img idx
# pos_8_im - pos in binary sequence
# used to compute 4) Start and end date of snow cover season
def get_cos_doy_snow_season(py_dates, pos_im, pos_8_im):
    cos_doy = np.zeros(pos_im.shape)
    ni,nj = pos_im.shape
    for i in range(ni):
        for j in range(nj):
            cos_doy[i,j] = indexes_to_cosdoy (py_dates, pos_im[i,j], pos_8_im[i,j])
        
    return cos_doy


def write_output_image(filepath, output_matrix, image_format, data_format, mask=None, output_projection=None, output_geotransform=None, no_data_value=None):
    
    driver = gdal.GetDriverByName(image_format)
    out_rows = np.size(output_matrix, 0)
    out_columns = np.size(output_matrix, 1)
    
    
    if mask is not None and mask is not 0:
        # TODO: check if output folder exists
        output = driver.Create(filepath, out_columns, out_rows, 2, data_format)
        mask_band = output.GetRasterBand(2)
        mask_band.WriteArray(mask)
        if no_data_value is not None:
            output_matrix[mask > 0] = no_data_value
    else:
        output = driver.Create(filepath, out_columns, out_rows, 1, data_format)
    
    if output_projection is not None:
        output.SetProjection(output_projection)
    if output_geotransform is not None:
        output.SetGeoTransform(output_geotransform)
    
    raster_band = output.GetRasterBand(1)
    if no_data_value is not None:
        raster_band.SetNoDataValue(no_data_value)
    raster_band.WriteArray(output_matrix)
    
    gdal.Warp(filepath, output, format="GTiff", outputBoundsSRS='EPSG:4326', xRes=output_geotransform[1], yRes=-output_geotransform[5], targetAlignedPixels=True)
    
    
    
    
    






In [12]:
if check_results:

    print('teste')
    snow_array = ['10111011', '11111111', '11100001', '10010000', '00011100', '11100011']

    snow_array1 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00011100', '11100000']])

    snow_array2 = np.array([['10111011', '11111111', '11100001'],
                           ['10010000', '00011100', '11100000']])

    snow_matrix_list = [snow_array1]
    snow_matrix_list.append(snow_array2)

    '''
    n_ant_snow = 0
    n_cons = 0
    for sr in snow_array:
        n_ant_snow, n_cons = count_consecutive_sc_days(sr, n_ant_snow, n_cons, min_sc_days = 2)
        #print(n_cons)

    if n_ant_snow >= 2:
        n_cons = n_cons + 1

    print(snow_array)
    print(n_cons)
    '''

    print('new cenas')
    print(count_of_major_consecutive_sc_days(snow_array[0]))

    num_of_1s = 0
    max_num_of_1s_so_far = 0
    last_car = '0'
    for s in ['11111111', '11111111' , '11111111' , '11111111']:
    
        num_of_1s, max_num_of_1s_so_far, last_car = count_of_major_consecutive_sc_days(s, num_of_1s, max_num_of_1s_so_far, last_car)
    
    print(num_of_1s, max_num_of_1s_so_far, last_car)



    print('now with matrices')

    print(snow_matrix_list)
    c = get_max_sc_consecutive_ndays (snow_matrix_list)

    print(c)
    
    
    # about start date snow
    
    
    
    snow_array = ['10111011', '11111111', '11100001', '10010000', '00011100', '11100011']
    snow_array = ['00000000', '00010000', '00000000', '10010000', '00011100', '11100011']

    pos_img1 = -1
    pos_img2 = -1
    pos_1st_snow = -1

    for idxsa in range(len(snow_array)):
    
        pos_img1, pos_img2, pos_1st_snow = find_start_day_snow_season_idx(snow_array[idxsa], idxsa, pos_img1, pos_img2, pos_1st_snow)
    
    print(pos_img1, pos_img2, pos_1st_snow)
    
    
    
    
    snow_array1 = np.array([['10111011', '11111111', '00000000'],
                            ['10010000', '00000000', '11100000']])

    snow_array2 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00000100', '11100000']])
    
    snow_array3 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00000000', '11100000']])

    snow_array4 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00011100', '11100000']])

    snow_array4 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00011100', '11100000']])

    snow_matrix_list = [snow_array1]
    snow_matrix_list.append(snow_array2)
    snow_matrix_list.append(snow_array3)
    snow_matrix_list.append(snow_array4)
    

    pos_im, pos_8 = get_start_day_snow_season (snow_matrix_list)

    print(pos_im)
    print(pos_8)
    
   

    snow_array = ['10111011', '11111111', '11100001', '10010000', '00011100', '11100011']
    snow_array = ['00000000', '00010000', '00000000', '10010000', '00011100', '11100011', '00000000', '11100011', '00000000', '00000000']

    pos_img1 = -1
    pos_img2 = -1
    pos_1st_snow = -1

    for idxsa in range(len(snow_array)):
        pos_img1, pos_img2, pos_1st_snow = find_end_day_snow_season_idx(snow_array[idxsa], idxsa, pos_img1, pos_img2, pos_1st_snow)

    print(pos_img1, pos_img2, pos_1st_snow)
    
    


    
    
    snow_array1 = np.array([['10111011', '11111111', '00000000'],
                            ['10010000', '11111111', '11100000']])

    snow_array2 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00000000', '11100000']])
    
    snow_array3 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '11100000', '11100000']])

    snow_array4 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00000000', '00000000']])

    snow_array4 = np.array([['10111011', '11111111', '11100001'],
                            ['10010000', '00000000', '00000000']])

    snow_matrix_list = [snow_array1]
    snow_matrix_list.append(snow_array2)
    snow_matrix_list.append(snow_array3)
    snow_matrix_list.append(snow_array4)
    

    pos_im, pos_8 = get_end_day_snow_season (snow_matrix_list)

    print(pos_im)
    print(pos_8)

teste
new cenas
(2, 3, '1')
(32, 32, '1')
now with matrices
[array([['10111011', '11111111', '11100001'],
       ['10010000', '00011100', '11100000']], dtype='|S8'), array([['10111011', '11111111', '11100001'],
       ['10010000', '00011100', '11100000']], dtype='|S8')]
[[ 3 16  4]
 [ 1  3  3]]
(3, 4, 4)
[[0 0 1]
 [0 3 0]]
[[0 0 0]
 [4 2 5]]
(8, 9, 7)
[[-1. -1. -1.]
 [-1.  3.  3.]]
[[-1. -1. -1.]
 [-1. -1. -1.]]


#### Auxiliary folders

In [13]:
#Create folders
#if not os.path.isdir(data_path):
#    os.mkdir(data_path)

if len(output_folder) > 0:
    if not os.path.isdir(output_folder):
        os.mkdir(output_folder)

if not os.path.isdir(temp_folder):
    os.mkdir(temp_folder)

#### Workflow

##### Group identifiers by date for the mosaicking

In [14]:
# group by date
input_identifiers_per_date = {}

for ii in input_identifiers:
    
    key = ii.split('/')[-1].split('.')[1]
    
    #print(ii.split('/')[-1].split('.')[1])
    
    year = int(key[1:5])
    days = int(key[5:8])
    date_str = datetime.datetime(year, 1, 1) + datetime.timedelta(days - 1)
    date_str = date_str.strftime("%Y-%m-%d")
    
    if date_str in input_identifiers_per_date:
        input_identifiers_per_date[date_str].append(ii)
    else:
        input_identifiers_per_date[date_str] = [ii]
        

for k in input_identifiers_per_date:
    print(k)
    
    #print(date_str)
    
    print(input_identifiers_per_date[k])
    
dates = [dt for dt in input_identifiers_per_date]
dates.sort()


2015-10-16
['MOD10A2.A2015289.h19v04.006.2016182032251.hdf', 'MOD10A2.A2015289.h19v05.006.2016182030630.hdf', 'MOD10A2.A2015289.h20v04.006.2016182032143.hdf', 'MOD10A2.A2015289.h20v05.006.2016182031542.hdf']
2016-05-08
['MOD10A2.A2016129.h19v04.006.2016140154151.hdf', 'MOD10A2.A2016129.h19v05.006.2016140153820.hdf', 'MOD10A2.A2016129.h20v04.006.2016140154121.hdf', 'MOD10A2.A2016129.h20v05.006.2016140153448.hdf']
2015-08-29
['MOD10A2.A2015241.h19v04.006.2016181062033.hdf', 'MOD10A2.A2015241.h19v05.006.2016181051646.hdf', 'MOD10A2.A2015241.h20v04.006.2016181053544.hdf', 'MOD10A2.A2015241.h20v05.006.2016181053542.hdf']
2016-07-19
['MOD10A2.A2016201.h19v04.006.2016215123536.hdf', 'MOD10A2.A2016201.h19v05.006.2016215123748.hdf', 'MOD10A2.A2016201.h20v04.006.2016215123826.hdf', 'MOD10A2.A2016201.h20v05.006.2016215123656.hdf']
2015-08-05
['MOD10A2.A2015217.h19v04.006.2016181040203.hdf', 'MOD10A2.A2015217.h19v05.006.2016181041147.hdf', 'MOD10A2.A2015217.h20v04.006.2016181040703.hdf', 'MOD10A2.

##### Mosaicking images

In [15]:

mosaic_files = []


#for g in input_identifiers_per_date:
for g in dates: # use dates instead of input_identifiers_per_date keys in order to be ordered

    print(g)
    
    subset_identifiers = input_identifiers_per_date[g]

    list_of_file = [os.path.join(data_path, fn) for fn in subset_identifiers]

    #list_of_file[0:4]

    mosaicGdal = createMosaicGDAL(list_of_file[0:4], '0 1', 'GTiff')

    nstr = list_of_file[0].split('/')[-1]

    mosaic_output_file_name = '.'.join([nstr.split('.')[0], nstr.split('.')[1], nameOfRegion['value'], 'tif'])

    mosaic_file = os.path.join(temp_folder, mosaic_output_file_name)

    mosaicGdal.run(mosaic_file)

    mosaic_files.append(mosaic_file)

2015-08-05
The mosaic file temp/MOD10A2.A2015217.CentralAsia.tif has been created
2015-08-13
The mosaic file temp/MOD10A2.A2015225.CentralAsia.tif has been created
2015-08-21
The mosaic file temp/MOD10A2.A2015233.CentralAsia.tif has been created
2015-08-29
The mosaic file temp/MOD10A2.A2015241.CentralAsia.tif has been created
2015-09-06
The mosaic file temp/MOD10A2.A2015249.CentralAsia.tif has been created
2015-09-14
The mosaic file temp/MOD10A2.A2015257.CentralAsia.tif has been created
2015-09-22
The mosaic file temp/MOD10A2.A2015265.CentralAsia.tif has been created
2015-09-30
The mosaic file temp/MOD10A2.A2015273.CentralAsia.tif has been created
2015-10-08
The mosaic file temp/MOD10A2.A2015281.CentralAsia.tif has been created
2015-10-16
The mosaic file temp/MOD10A2.A2015289.CentralAsia.tif has been created
2015-10-24
The mosaic file temp/MOD10A2.A2015297.CentralAsia.tif has been created
2015-11-01
The mosaic file temp/MOD10A2.A2015305.CentralAsia.tif has been created
2015-11-09
The m

In [16]:
mosaic_files

['temp/MOD10A2.A2015217.CentralAsia.tif',
 'temp/MOD10A2.A2015225.CentralAsia.tif',
 'temp/MOD10A2.A2015233.CentralAsia.tif',
 'temp/MOD10A2.A2015241.CentralAsia.tif',
 'temp/MOD10A2.A2015249.CentralAsia.tif',
 'temp/MOD10A2.A2015257.CentralAsia.tif',
 'temp/MOD10A2.A2015265.CentralAsia.tif',
 'temp/MOD10A2.A2015273.CentralAsia.tif',
 'temp/MOD10A2.A2015281.CentralAsia.tif',
 'temp/MOD10A2.A2015289.CentralAsia.tif',
 'temp/MOD10A2.A2015297.CentralAsia.tif',
 'temp/MOD10A2.A2015305.CentralAsia.tif',
 'temp/MOD10A2.A2015313.CentralAsia.tif',
 'temp/MOD10A2.A2015321.CentralAsia.tif',
 'temp/MOD10A2.A2015329.CentralAsia.tif',
 'temp/MOD10A2.A2015337.CentralAsia.tif',
 'temp/MOD10A2.A2015345.CentralAsia.tif',
 'temp/MOD10A2.A2015353.CentralAsia.tif',
 'temp/MOD10A2.A2015361.CentralAsia.tif',
 'temp/MOD10A2.A2016001.CentralAsia.tif',
 'temp/MOD10A2.A2016009.CentralAsia.tif',
 'temp/MOD10A2.A2016017.CentralAsia.tif',
 'temp/MOD10A2.A2016025.CentralAsia.tif',
 'temp/MOD10A2.A2016033.CentralAsi

##### Load images

In [17]:
projection, geotransform, no_data_value, data_type = get_metadata(mosaic_files[0])
    
ml = mosaic_files
if load_all_data:
    ml = get_matrix_list(mosaic_files)

ml

['temp/MOD10A2.A2015217.CentralAsia.tif',
 'temp/MOD10A2.A2015225.CentralAsia.tif',
 'temp/MOD10A2.A2015233.CentralAsia.tif',
 'temp/MOD10A2.A2015241.CentralAsia.tif',
 'temp/MOD10A2.A2015249.CentralAsia.tif',
 'temp/MOD10A2.A2015257.CentralAsia.tif',
 'temp/MOD10A2.A2015265.CentralAsia.tif',
 'temp/MOD10A2.A2015273.CentralAsia.tif',
 'temp/MOD10A2.A2015281.CentralAsia.tif',
 'temp/MOD10A2.A2015289.CentralAsia.tif',
 'temp/MOD10A2.A2015297.CentralAsia.tif',
 'temp/MOD10A2.A2015305.CentralAsia.tif',
 'temp/MOD10A2.A2015313.CentralAsia.tif',
 'temp/MOD10A2.A2015321.CentralAsia.tif',
 'temp/MOD10A2.A2015329.CentralAsia.tif',
 'temp/MOD10A2.A2015337.CentralAsia.tif',
 'temp/MOD10A2.A2015345.CentralAsia.tif',
 'temp/MOD10A2.A2015353.CentralAsia.tif',
 'temp/MOD10A2.A2015361.CentralAsia.tif',
 'temp/MOD10A2.A2016001.CentralAsia.tif',
 'temp/MOD10A2.A2016009.CentralAsia.tif',
 'temp/MOD10A2.A2016017.CentralAsia.tif',
 'temp/MOD10A2.A2016025.CentralAsia.tif',
 'temp/MOD10A2.A2016033.CentralAsi

##### Count of number of snow days during the season

In [ ]:
snow_ndays = get_snow_ndays(ml)

snow_ndays

##### Count of number of consecutive snow cover days

In [ ]:
snow_max_cons_ndays = get_max_sc_consecutive_ndays(ml)

snow_max_cons_ndays

##### The start day

In [ ]:
# 1. compute positions of first snow
pos_im, pos_8 = get_start_day_snow_season (ml)

# 2. get list of dates from image names
py_dates = [datetime.datetime.strptime(d, "%Y-%m-%d").date() for d in dates] # dates in datetime format


# 3. compute doy of first snow based on 1. and 2.
cos_doy_start_day = get_cos_doy_snow_season(py_dates, pos_im, pos_8)

cos_doy_start_day

##### The end day

In [ ]:
# 1. compute positions of first snow
pos_im, pos_8 = get_end_day_snow_season (ml)

# 2. get list of dates from image names
py_dates = [datetime.datetime.strptime(d, "%Y-%m-%d").date() for d in dates] # dates in datetime format

# 3. compute doy of first snow based on 1. and 2.
cos_doy_end_day = get_cos_doy_snow_season(py_dates, pos_im, pos_8)

cos_doy_end_day

##### Check result (Count of number of snow days during the season)

In [ ]:
if check_results:
    
    import matplotlib
    import matplotlib.pyplot as plt

    fig = plt.figure()
    plt.imshow(snow_ndays)
    plt.show()

##### Check result (Count of number of consecutive snow cover days)

In [ ]:
if check_results:
    
    import matplotlib
    import matplotlib.pyplot as plt

    fig = plt.figure()
    plt.imshow(snow_max_cons_ndays)
    plt.show()

##### Check result (The start day)

In [ ]:
if check_results:
    
    import matplotlib
    import matplotlib.pyplot as plt

    fig = plt.figure()
    plt.imshow(cos_doy_start_day)
    plt.show()

##### Check result (The end day)

In [ ]:
if check_results:
    
    import matplotlib
    import matplotlib.pyplot as plt

    fig = plt.figure()
    plt.imshow(cos_doy_end_day)
    plt.show()

##### Write image (Count of number of snow days during the season)

In [ ]:

snow_ndays_img_name = 'snow_ndays' + '_' + nameOfRegion['value'] + '_' + dates[0] + '_' + dates[-1] + '.tif'
snow_ndays_img_name = os.path.join(output_folder, snow_ndays_img_name)

write_output_image(snow_ndays_img_name, snow_ndays, 'GTiff', gdal.GDT_UInt16, None, projection, geotransform, no_data_value)


##### Write image (Count of number of consecutive snow cover days)

In [ ]:

snow_cons_ndays_img_name = 'snow_cons_ndays' + '_' + nameOfRegion['value'] + '_' + dates[0] + '_' + dates[-1] + '.tif'
snow_cons_ndays_img_name = os.path.join(output_folder, snow_cons_ndays_img_name)

write_output_image(snow_cons_ndays_img_name, snow_max_cons_ndays, 'GTiff', gdal.GDT_UInt16, None, projection, geotransform, no_data_value)

##### Write image (The start date)

In [ ]:

snow_start_date_img_name = 'snow_start_date' + '_' + nameOfRegion['value'] + '_' + dates[0] + '_' + dates[-1] + '.tif'
snow_start_date_img_name = os.path.join(output_folder, snow_start_date_img_name)

write_output_image(snow_start_date_img_name, cos_doy_start_day, 'GTiff', gdal.GDT_Float32, None, projection, geotransform, -999)

##### Write image (The end date)

In [ ]:

snow_end_date_img_name = 'snow_end_date' + '_' + nameOfRegion['value'] + '_' + dates[0] + '_' + dates[-1] + '.tif'
snow_end_date_img_name = os.path.join(output_folder, snow_end_date_img_name)

write_output_image(snow_end_date_img_name, cos_doy_end_day, 'GTiff', gdal.GDT_Float32, None, projection, geotransform, -999)

#### Remove temporay files and folders

In [ ]:
rm_cfolder(temp_folder)

os.rmdir(temp_folder)